export enum MutationEnum {
    ADICIONA_PROJETO = 'ADICIONA_PROJETO',
    ALTERA_PROJETO = 'ALTERA_PROJETO',
    EXCLUIR_PROJETO = 'EXCLUIR_PROJETO',
    DEFINIR_PROJETO = 'DEFINIR_PROJETO',
    NOTIFICAR = 'NOTIFICAR'
}